apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-liieyw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-liieyw
    app.kubernetes.io/part-of: jvm-build-suite-application-kwfv
  name: jvm-build-suite-component-liieyw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-liieyw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-liieyw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-vvmb-tenant/jvm-build-suite-application-kwfv/jvm-build-suite-component-liieyw@sha256:ea440535f476a7837e1126e92c83d5ddb1f3ee45824694fc6f7ea7165d8a21ec
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
